curl -v -X GET "http://localhost:4005/validate" \
     -H "Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlckB0ZXN0LmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc3MTEzMzUwOSwiZXhwIjoxNzcxMTY5NTA5fQ.9kb3iPm4_r-mF24dA5MrWZquOLQgI-QnIJPt2JDWk6o"
     
     
curl -v -X GET "http://localhost:4004/auth/validate" \
     -H "Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlckB0ZXN0LmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc3MTEzNjA1NCwiZXhwIjoxNzcxMTcyMDU0fQ.23X_T3y-AJYgj-mCYxyMcZTDjQw3TIcRo_AoN-GGNI8"